"""Generate the knowledge-base status report (acceptance of Part 1).

Output: knowledge/db/kb_report.md — measured numbers, not declared ones.
Usage:  python -m kb.report
"""
from __future__ import annotations

import json
import sqlite3
from collections import Counter
from datetime import date
from pathlib import Path

import yaml

from kb.schemas import Reference


def main() -> None:
    refs = [Reference(**json.loads(l)) for l in
            Path("knowledge/db/references.jsonl").read_text().splitlines() if l.strip()]
    claims = [json.loads(l) for l in
              Path("knowledge/db/kosmos_claims.jsonl").read_text().splitlines() if l.strip()]
    conn = sqlite3.connect("knowledge/db/papers.sqlite")
    catalog = yaml.safe_load(Path("catalog/foxes.yaml").read_text())["foxes"]
    tools = yaml.safe_load(Path("catalog/tools.yaml").read_text())["tools"]

    in_scope = [r for r in refs if set(r.queries) & {"L1", "L2"}]
    papers = {r.paper_id for r in refs if r.paper_id}
    downloaded = {r.paper_id for r in refs if r.fetch_status == "downloaded"}
    n_sections = conn.execute("SELECT COUNT(*) FROM paper_sections").fetchone()[0]
    quality = Counter(r[0] for r in conn.execute(
        "SELECT extraction_quality FROM papers WHERE extraction_quality IS NOT NULL"))
    fetch = Counter(r.fetch_status for r in refs)
    resolve = Counter(r.resolve_status for r in refs)
    status = Counter(f["status"] for f in catalog)
    reports = sorted(Path("knowledge/kosmos").rglob("*.pdf"))

    lines = [
        "# Knowledge-base status (Part 1)", "",
        f"Generated by `python -m kb.report` on {date.today().isoformat()}. "
        "Every number comes from the artifacts, not from the plan.", "",
        "## Kosmos ingestion", "",
        f"- reports processed: {len(reports)} ("
        + ", ".join(f"`{p.name}`" for p in reports) + ")",
        f"- cited claims extracted: **{len(claims)}**",
        f"- references: **{len(refs)}** "
        f"({sum(1 for r in refs if r.ref_kind == 'listed')} with a formal entry in the report, "
        f"{sum(1 for r in refs if r.ref_kind == 'inline')} only named in the body)",
        f"- distinct works after deduplication: **{len(papers)}**",
        f"- references in scope L1/L2 (the ones that feed E1's catalog): {len(in_scope)}; "
        f"the rest belong to L3 (credit assignment), out of E1's scope",
        "",
        "The report's reference section is cut off inside entry `[12.3]`, so groups "
        "`[13.1]`–`[23.1]` exist only as mentions in the body. That is why the ingestor extracts "
        "both kinds and the metadata resolution works with both.",
        "",
        "## Metadata resolution", "",
        "| Status | References |", "|---|---|",
    ]
    for k, v in resolve.most_common():
        lines.append(f"| `{k}` | {v} |")
    lines += [
        "",
        f"Resolved with confidence: **{resolve['resolved']}/{len(refs)}** "
        f"({resolve['resolved'] / len(refs):.0%}). The `ambiguous` ones are in "
        "`knowledge/db/review_queue.md` with their citation context, so the review does not "
        "require opening the PDF.",
        "",
        "## PDF download", "",
        "| Status | References |", "|---|---|",
    ]
    for k, v in fetch.most_common():
        lines.append(f"| `{k}` | {v} |")
    lines += [
        "",
        f"PDFs obtained through legitimate routes: **{len(downloaded)} distinct works** of {len(papers)}. "
        "Sources used: OpenAlex open-access locations, arXiv, Semantic Scholar and the direct "
        "links carried by the report itself. No paywall was circumvented: whatever has no open "
        "route stays in the review queue for download with institutional access.",
        "",
        "**Rule applied:** nothing is downloaded for a reference whose metadata is not resolved. "
        "Downloading by title search without confirming author and year attaches the wrong PDF "
        "to the reference, which is worse than having none.",
        "",
        "## Text and database", "",
        f"- papers with section-wise extracted text: {len(downloaded)}",
        f"- sections indexed: {n_sections}",
        f"- extraction quality: " + ", ".join(f"{k}={v}" for k, v in quality.items()),
        f"- database: `knowledge/db/papers.sqlite` with a full-text index (FTS5) over the sections",
        "",
        "## Catalog", "",
        f"- foxes: **{len(catalog)}** — " + ", ".join(f"{v} `{k}`" for k, v in status.most_common()),
        f"- tools: {len(tools)} — " +
        ", ".join(f"{v} `{k}`" for k, v in Counter(t['status'] for t in tools).most_common()),
        "",
        "| Fox | Status | Estimates | Beats the control |", "|---|---|---|---|",
    ]
    for fox in catalog:
        verdict = ("yes" if fox["status"] == "validated" else
                   "no (see report)" if fox["status"] == "implemented" else "not evaluated")
        lines.append(f"| `{fox['fox_id']}` | {fox['status']} | "
                     f"{', '.join(fox.get('estimates') or [])} | {verdict} |")
    lines += ["", "The full validation reports are in "
              "`foxes/<fox_id>/validation_report.md`.", ""]
    Path("knowledge/db/kb_report.md").write_text("\n".join(lines), encoding="utf-8")
    print("-> knowledge/db/kb_report.md")


if __name__ == "__main__":
    main()
