"""Program debrief, written *from* the computed metrics (task 3.3).

Rule §3: no LLM as judge. This module evaluates nothing; it takes the numbers that
`feedback.metrics` already computed and lays them out as a readable report.
"""
from __future__ import annotations

import argparse
import json
from datetime import date
from pathlib import Path

import pandas as pd

from feedback.metrics import (attribution_leave_one_out, calibration_metrics, outcome_metrics,
                              resolve_hypotheses)
from gym.case import CaseBundle


def build_report(program_id: str, runs_dir: Path = Path("runs")) -> Path:
    root = runs_dir / program_id
    events = [json.loads(l) for l in (root / "events.jsonl").read_text().splitlines() if l.strip()]
    # Defensive: should a trace file ever hold more than one run, the last one rules.
    start = [e for e in events if e["kind"] == "program_start"][-1]
    end = [e for e in events if e["kind"] == "program_end"][-1]
    config = start["payload"]["config"]
    bundle = CaseBundle.load(config["case_id"])

    outcome = outcome_metrics(bundle, end["payload"])
    calib = calibration_metrics(bundle, root / "beliefs.parquet")
    attrib = attribution_leave_one_out(bundle, root / "beliefs.parquet")
    hyps = resolve_hypotheses(bundle, program_id, runs_dir=runs_dir)
    roles = bundle.role_ids()
    issue_id = bundle.domain().issue_ids[0]

    lines = [
        f"# Debrief — {program_id}", "",
        f"Generated by `python -m feedback.report --program {program_id}` on "
        f"{date.today().isoformat()}. Every figure comes from the trace and from the case's "
        f"sealed truth; no language model scores anything here.", "",
        "## Configuration", "",
        f"- case: `{config['case_id']}` · agent: `{config['agent']}` · "
        f"personality: `{config['personality']}`",
        f"- tau per party: {config['tau']} · lambda per party: {config['lambda']}",
        f"- seed: {config['seed']} · horizon: {config['max_rounds']} rounds",
        f"- validated foxes available: {', '.join(config['foxes_validated'])}",
        "",
        "## Outcome", "",
    ]
    if outcome.agreement:
        price = outcome.agreed_offer[issue_id]
        lines += [f"**Agreement at {price:,.0f} after {outcome.rounds} rounds** ({outcome.ended_by})."]
    else:
        lines += [f"**Impasse after {outcome.rounds} rounds** ({outcome.ended_by})."]
    lines += [
        "",
        f"- true ZOPA: [{outcome.true_zopa[0]:,.0f}, {outcome.true_zopa[1]:,.0f}]",
        f"- realised utilities: " +
        ", ".join(f"{r} {outcome.utilities[r]:.3f}" for r in roles),
        f"- joint utility {outcome.joint_utility:.3f} · Nash product "
        f"{outcome.nash_product:.4f}",
        f"- distance to the Pareto frontier: **{outcome.dist_to_pareto:.4f}** "
        f"(value left on the table)",
        f"- distance to the Nash point: {outcome.dist_to_nash:.4f} · to Kalai–Smorodinsky: "
        f"{outcome.dist_to_ks:.4f}",
        f"- surplus split: " +
        ", ".join(f"{r} {outcome.surplus_split[r]:.0%}" for r in roles),
        "",
        "## Calibration of the belief about the counterpart", "",
        "Each party estimates the other's reservation value, in the other's utility scale. The "
        "truth comes from the confidential material the gym sealed before the first round. The "
        "control (a flat prior) is scored on the same rounds: a belief that does not beat it "
        "carries no information.",
        "",
    ]
    if not calib.empty:
        agg = {"rounds": ("round", "count"), "mean_error": ("abs_error", "mean"),
               "crps": ("crps", "mean"), "log_score": ("log_score", "mean"),
               "cover50": ("cover50", "mean"), "cover90": ("cover90", "mean"),
               "final_sd": ("sd", "last")}
        if "control_crps" in calib.columns:
            agg["control_crps"] = ("control_crps", "mean")
            agg["control_log_score"] = ("control_log_score", "mean")
        summary = calib.groupby("party").agg(**agg).round(4)
        lines += [summary.to_markdown(), ""]
        for party, group in calib.groupby("party"):
            trajectory = " → ".join(f"r{int(r.round)}: {r.sd:.3f}" for r in
                                    group.itertuples() if int(r.round) % 2 == 1)
            lines += [f"- **{party}**: spread of the belief by round — {trajectory}",
                      f"  truth {group.true_rv.iloc[0]:.4f} · final median "
                      f"{group['median'].iloc[-1]:.4f}"]
        lines.append("")
    else:
        lines += ["_No belief data recorded._", ""]

    lines += ["## Per-fox attribution (leave-one-out)", ""]
    if not attrib.empty:
        table = attrib.groupby(["party", "fox_id"]).agg(
            rounds=("round", "count"),
            mean_log_score_contribution=("delta_log_score", "mean")).round(4)
        lines += [table.to_markdown(), "",
                  "A positive contribution means removing that fox worsens the pooled belief: "
                  "it was adding information. Computed over the pool that decided (in-scope, "
                  "validated foxes); the control is not a member.", ""]
    else:
        lines += ["_Fewer than two foxes in scope in every round: no attribution possible._", ""]

    lines += ["## Hypotheses", ""]
    for party, scores in hyps.items():
        if scores["n_total"] == 0:
            lines.append(f"- **{party}**: registered no hypotheses.")
            continue
        brier = scores.get("brier_mean")
        lines.append(f"- **{party}**: {scores['n_total']} registered, "
                     f"{scores['n_resolved']} resolved"
                     + (f", mean Brier {brier:.3f}" if brier is not None else ""))
    saved = {e["party"]: e["payload"] for e in events if e["kind"] == "hypotheses_saved"}
    for party, payload in saved.items():
        lines.append(f"  - {party}: {payload.get('n_updates_during_rounds', 0)} belief "
                     f"update(s) during the rounds")
    lines += ["", "## Cost", ""]
    fox_calls = [e for e in events if e["kind"] == "fox_call"]
    memos = [e for e in events if e["kind"] == "decision_memo"]
    llm_tokens = sum(int((e["payload"].get("memo", {}).get("llm_usage") or {})
                         .get("total_tokens", 0) or 0) for e in memos)
    lines += [f"- events in the trace: {len(events)} · decision memos: {len(memos)}",
              f"- fox calls recorded: {len(fox_calls)}",
              f"- model tokens in the negotiation: {llm_tokens}",
              "",
              "## Isolation", "",
              f"- {end['payload']['isolation']['checks']} canary checks, "
              f"{end['payload']['isolation']['leaks']} leaks.", ""]

    target = root / "feedback" / "report.md"
    target.parent.mkdir(parents=True, exist_ok=True)
    target.write_text("\n".join(lines), encoding="utf-8")
    (root / "feedback" / "metrics.json").write_text(
        json.dumps({"outcome": outcome.to_dict(), "hypotheses": hyps}, indent=2,
                   ensure_ascii=False, default=str), encoding="utf-8")
    if not calib.empty:
        calib.to_csv(root / "feedback" / "calibration.csv", index=False)
    if not attrib.empty:
        attrib.to_csv(root / "feedback" / "attribution.csv", index=False)
    return target


def main() -> None:
    ap = argparse.ArgumentParser()
    ap.add_argument("--program", required=True)
    ap.add_argument("--runs-dir", default="runs")
    args = ap.parse_args()
    path = build_report(args.program, Path(args.runs_dir))
    print(f"-> {path}")


if __name__ == "__main__":
    main()
